### ISSUE TITLE
Iconfont attempts to resolve in mixin's body

### ISSUE THREAD

**Issue by TuxujPes** [jantimon/iconfont-webpack-plugin#15]
Hi,
thanks for an awesome plugin!
I am trying to use plugin with scss mixins and it seems it tries to resolve `font-icon` on mixin level.

example of code:
```
.custom- icon {

  @mixin icon($name) {
    &:before {
      font-icon: url("./images/#{$name}.svg") !important;
    }
  }

  &-paper-plane { @include icon("paper-plane") }
}
```

results in: 
`index.js:16 Error: Module build failed: Error: Can't resolve './images/#{$name}.svg'`

webpack styles part:
```
       test: /\.(css|scss)$/,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: { sourceMap: true }
          },
          {
            loader: 'sass-loader',
            options: { sourceMap: true }
          },
          {
            loader: 'postcss-loader',
            options: {
              plugins: (loader) => [ new IconfontWebpackPlugin(loader) ]
            }
          }
        ]
```

Am I doing something wrong or this is an expected behavior?

**Comment by jantimon** [comment]
Your current configuration works like this:

`css = style-loader(css-loader(sass-loader(postcss-loader(yourCssFile)))`

As you see your css is processed first by the post-css loader where the icon font is generated.  After that you use sass for the result.  

To resolve this issue you have to switch the sass and postcss loaders so that it will first generate the css which can be used by the IconfontWebpackPlugin
