### ISSUE TITLE
Eliminate font-family and font-weight from font-icon-glyph

### ISSUE THREAD

**Issue by sergeymorkovkin** [jantimon/iconfont-webpack-plugin#19]
These CSS properties should not duplicate by default, I think. Simply because most users will put it in a general selector, e.g.:

```
[class^="icon-"], [class*=" icon-"] {
  /* use !important to prevent issues with browser extensions that change fonts */
  font-family: iconfont !important;
  speak: none;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;

  /* Better Font Rendering =========== */
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```
In this case it's redundant CSS weight, which looks more like a problem. At least, this might become an option.

**Comment by sergeymorkovkin** [comment]
@jantimon I agree it's not so relevant when using Gzip (I've got 228 bytes with "iconfont" prefix), but on the other hand it's taking around 48K in plain CSS. Again, agree, not a big deal in development, but what's the point? I mean, why do we need this redundancy? Is there any positive goal I'm not aware of? Jan, please don't get me wrong. I'm only trying to bring in little more perfection into your work, which is already brilliant.

**Comment by sergeymorkovkin** [comment]
Got your answer in #18. We're talking about different use-cases. For my perspective following things are missing:

1. Free from need to manually update font-family in all-icons selector
2. Redundancy with font-family and font-weight properties
3. Both 1 and 2 contradict the use of custom all-icons selectors
4. Ability to save iconfile instead of base64 (separate issue)

I really think this is a popular scenario that should also be supported. What do you think?

**Comment by jantimon** [comment]
Hey @sergeymorkovkin 

I am happy that you take so much time to investigate this issue and to move this plugin forward.  
The effort of maintaining a solution for 228 bytes which encourages needles performance optimisations doesn't make much sense for me.

One design goal of this plugin is `to keep it as simple as possible`.  
Simplicity always requires to reduce features.  
I would prefer a solution which is perfect for 90% of the projects rather than supporting 98% and having a lot of very advanced options.

Adding many different `font-icon-...` commands will create many different use cases and people have to study all possible solutions carefully before using it correctly.  

Maybe we should also remove the `icon-font-glyph` again.  
What do you think?

**Comment by sergeymorkovkin** [comment]
@jantimon My opinion is that it's generally a good idea to provide meaningful options to end users. By options I mean some settings with their defaults provided. This way, there is a common and widely-used use-case, while other use-cases are also possible by setting different option values. Users won't need to read/configure anything before using a plugin. If it doesn't sound reasonable, feel free to close this issue. And, by the way, I'm [not the only one](https://github.com/mikaelguillin/iconfont-webpack-plugin/commit/893d46216a7aafcbb8a96c76b0ce17b3edb5b006) needing this.

**Comment by jantimon** [comment]
Just found your approach in  an old legacy project:

```
[class^="icon-"], [class*=" icon-"] {
  font-family: iconfont !important;
}
```

It had two issues:

1. the selectors are quite slow - it has to do partial selection for all elements in the dom
2. there were two different css files on the page which both provided a icon font with this syntax and overwrote each other

Be careful this approach is slow and dangerous
